### PR TITLE
Enable fail-fast mode for BVT

### PR DESCRIPTION
**Pull request by JustinKuli**
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

### CODE REVIEW

**Comment by ycao56** [comment]
Fail fast was intentionally off for canary. Now since canary is moving to BVT, I assume this is asked by CICD team?. If yes, we can just update
https://github.com/stolostron/grc-ui/blob/52943355e051f508e2f3fffd0f97aae3a2f0fce0/build/run-docker-tests.sh#L45-L50
Today, it is fail fast everywhere except canary.

**Comment by ycao56** [comment]
@JustinKuli is this for 2.4 or main? The test won't work when grc-ui pod is pulled out of the build. So the test needs to be removed from canary

**Comment by JustinKuli** [comment]
@ycao56 this is for current BVT. I hadn't noticed that other configuration point, but that would make more sense. We would want fail-fast on BVT. SVT would still run all of them.

The background is that when the policy framework is very unhealthy (recently happening more often because of changes in the way things are deployed), the UI tests will take 3+ hours and timeout the job. Because of the way it times out, it messes up test reporting for the entire product.

**Comment by JustinKuli** [comment]
@ycao56 is this a better approach? https://github.com/stolostron/canary-scripts/pull/252

**Pull request closed without merging**
