### PR TITLE
npm update follow-redirects

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

regarding: https://github.com/stolostron/backlog/issues/19486

Executed `npm audit fix`

### CODE REVIEW

**Comment by Randy424** [comment]
@ycao56  I reverted my changes and ran npm audit fix again, but with npm 6.14.16. My previous changes used a newer version and resulted in unneeded alterations to the package-lock.json.

**Comment by Randy424** [comment]
@ycao56 Reverted the changes again, this branch is now identical to [stolostron:release-2.4](https://github.com/stolostron/grc-ui/tree/release-2.4). e2e seems to be failing regardless of the changes present on the branch?

**Comment by ycao56** [comment]
@Randy424 The e2e failure is due to running out of clusters in clusterpool. 
However, this PR now contains no file change. What is going on here?

**Comment by Randy424** [comment]
@ycao56 I see. Thanks and sorry for the confusion. I reverted my changes to see if failure would occur on when there were no changes on the branch. I suppose it was an unorthodox method of testing, I wasn't at all familiar with the error. I will push my changes back up in a moment.

**Comment by Randy424** [comment]
/hold
...will also hold merge until 2.4.3 zstream open.s

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
