### PR TITLE
Remove the Ansible automation modal test

### PR DESCRIPTION
**Pull request by mprahl**
This has been flaky for years and the Console squad and GRC squad have not figured out how to make this work consistently.

A new approach was taken in the 2.5 console rewrite, so this test will be removed in 2.4. The QE E2E tests handle this test case, so there is still coverage before a new release.

Relates:
https://github.com/stolostron/backlog/issues/17369
https://github.com/stolostron/backlog/issues/24097

### CODE REVIEW

**Review by ChunxiAlexLuo — APPROVED** [review]
/lgtm

**Review by JustinKuli — APPROVED** [review]
Seems fine to me. It's possible that cicd will notice we are running fewer tests? But that might not be a problem. And only removing the tests that use the "configure" button would be non-trivial (I'd bet that some other tests click on the button to create the automation).

**Comment by dhaiducek** [comment]
/retest

Looks like there might be some networking issues here (though the last two failures were the same, so maybe third time's the charm?)

**Comment by dhaiducek** [comment]
Bummer. Looks like something is off with the config file. Let me know if you want someone to dig into it or if you'd prefer to override it for now...

**Comment by mprahl** [comment]
> Bummer. Looks like something is off with the config file. Let me know if you want someone to dig into it or if you'd prefer to override it for now...

I tried to reproduce the issue locally but the tests would run.

I'll merge it now and file an issue in the backlog.

**Comment by mprahl** [comment]
Here is the GitHub issue for next sprint:
https://github.com/stolostron/backlog/issues/25708

**Pull request merged**
